# Pre-commit (https://pre-commit.com)

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args: [--maxkb=128]
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-illegal-windows-names
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
  #
  # Run linters (text)
  #
  - repo: https://github.com/hukkin/mdformat
    rev: 1.0.0
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-gfm
          - mdformat-gfm-alerts
  - repo: https://github.com/crate-ci/typos
    rev: v1.48.0
    hooks:
      - id: typos
        # Override the hook's default behavior that fixes alleged typos
        args: [--sort, --force-exclude]
  #
  # Run linters (shell)
  #
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
      - id: shellcheck
        # Require that only the most serious problems be addressed
        args: [--severity=warning]
  #
  # Run linters (Python)
  #
  - repo: https://github.com/PyCQA/isort
    rev: 8.0.1
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 26.5.1
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/bandit
    rev: 1.9.4
    hooks:
      - id: bandit
        args: [-c, pyproject.toml]
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        language: system
        entry: mypy
        types: [python]
      - id: pyright
        name: pyright
        language: system
        entry: pyright
        types: [python]
      - id: pylint
        name: pylint
        language: system
        entry: pylint
        types: [python]
